// <auto-generated />
using System;
using Fileuploaddbc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fileuploaddbc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fileuploaddbc.Models.FileOnDatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileUploadViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileUploadViewModelId");

                    b.ToTable("FilesOnDatabase");
                });

            modelBuilder.Entity("Fileuploaddbc.Models.FileOnFileSystemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileUploadViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileUploadViewModelId");

                    b.ToTable("FilesOnFileSystem");
                });

            modelBuilder.Entity("Fileuploaddbc.Models.FileUploadViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedOn")
                        .HasMaxLength(15)
                        .HasColumnType("datetime2")
                        .IsFixedLength(true);

                    b.Property<string>("Description")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("FileType")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength(true);

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(2000)
                        .HasColumnType("nchar(2000)")
                        .IsFixedLength(true);

                    b.HasKey("Id")
                        .HasName("PK_Products_B40CC6CD73B27013");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("Fileuploaddbc.Models.FileOnDatabaseModel", b =>
                {
                    b.HasOne("Fileuploaddbc.Models.FileUploadViewModel", null)
                        .WithMany("FilesOnDatabase")
                        .HasForeignKey("FileUploadViewModelId");
                });

            modelBuilder.Entity("Fileuploaddbc.Models.FileOnFileSystemModel", b =>
                {
                    b.HasOne("Fileuploaddbc.Models.FileUploadViewModel", null)
                        .WithMany("FilesOnFileSystem")
                        .HasForeignKey("FileUploadViewModelId");
                });

            modelBuilder.Entity("Fileuploaddbc.Models.FileUploadViewModel", b =>
                {
                    b.Navigation("FilesOnDatabase");

                    b.Navigation("FilesOnFileSystem");
                });
#pragma warning restore 612, 618
        }
    }
}
